import fs from 'fs-extra';
import { getEnvFilePath } from './paths.js';
import { logger } from '../logger/logger.js';

/**
 * Environment variable yönetimi
 */
export class EnvManager {
  private envFilePath: string;

  constructor(projectPath: string) {
    this.envFilePath = getEnvFilePath(projectPath);
  }

  /**
   * Tüm environment variable'ları oku
   */
  async getAll(): Promise<Record<string, string>> {
    if (!(await fs.pathExists(this.envFilePath))) {
      return {};
    }

    try {
      const content = await fs.readFile(this.envFilePath, 'utf-8');
      const vars: Record<string, string> = {};

      for (const line of content.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) {
          continue;
        }

        const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
        if (match) {
          const [, key, value] = match;
          // Değeri unquote et (eğer tırnak içindeyse)
          vars[key] = value.replace(/^["']|["']$/g, '');
        }
      }

      return vars;
    } catch (error: any) {
      logger.error(`Env dosyası okuma hatası: ${error.message}`, 'env-manager', error);
      return {};
    }
  }

  /**
   * Environment variable ekle/güncelle
   */
  async set(key: string, value: string): Promise<void> {
    const vars = await this.getAll();
    vars[key] = value;
    await this.saveAll(vars);
  }

  /**
   * Environment variable sil
   */
  async unset(key: string): Promise<void> {
    const vars = await this.getAll();
    delete vars[key];
    await this.saveAll(vars);
  }

  /**
   * Birden fazla environment variable ekle/güncelle
   */
  async setMultiple(vars: Record<string, string>): Promise<void> {
    const existing = await this.getAll();
    const merged = { ...existing, ...vars };
    await this.saveAll(merged);
  }

  /**
   * Tüm environment variable'ları kaydet
   */
  private async saveAll(vars: Record<string, string>): Promise<void> {
    let content = '# Environment Variables\n';
    content += '# Generated by Raillmy\n\n';

    // Alfabetik sırayla kaydet
    const sortedKeys = Object.keys(vars).sort();
    for (const key of sortedKeys) {
      const value = vars[key];
      // Özel karakterler varsa tırnak içine al
      if (value.includes(' ') || value.includes('=') || value.includes('#')) {
        content += `${key}="${value}"\n`;
      } else {
        content += `${key}=${value}\n`;
      }
    }

    await fs.writeFile(this.envFilePath, content);
    logger.info(`Environment variables kaydedildi: ${this.envFilePath}`, 'env-manager');
  }

  /**
   * Environment variable dosyasını yedekle
   */
  async backup(): Promise<string> {
    if (!(await fs.pathExists(this.envFilePath))) {
      throw new Error('Env dosyası bulunamadı');
    }

    const backupPath = `${this.envFilePath}.backup.${Date.now()}`;
    await fs.copy(this.envFilePath, backupPath);
    logger.info(`Env dosyası yedeklendi: ${backupPath}`, 'env-manager');
    return backupPath;
  }

  /**
   * Yedekten geri yükle
   */
  async restore(backupPath: string): Promise<void> {
    if (!(await fs.pathExists(backupPath))) {
      throw new Error('Yedek dosyası bulunamadı');
    }

    await fs.copy(backupPath, this.envFilePath);
    logger.info(`Env dosyası geri yüklendi: ${backupPath}`, 'env-manager');
  }
}

